# これは OTL 1.4 用の設定ファイルです。
# 実行時に、コマンドラインオプションとして -f (このファイルの名前) を渡すことで使用できます。
# 例: java GalaxyTransformer -f galaxyconfig.properties

# このファイルの文法は、Javaのプロパティファイルの仕様に準じます。
# この行のように、'#' から始まる行はコメント行であり、動作に影響を与えません。

# 後で何分の一の倍率にするか
scale = 1

# 7.5等星の半径 (mm)
star-radius-7.5 = 0.125

# ドームの半径 (mm)
dome-radius = 6000

# ドームの中心から投影機中心へのベクトルの赤道面に平行な成分 (mm)
projector-horizontal = 300

# ドームの中心から投影機中心へのベクトルの赤道面に垂直な成分 (mm)
projector-vertical = 200

# 投影機の中心と原板の中心の間の距離 (mm)
plate-distance = 50

# 最輝星の等級
galaxy.star.maximum = 7.5

# 最微星の等級
galaxy.star.minimum = 10

# 横に各天のユニットをいくつ配置するか
plate.column = 1

# 縦に各天のユニットをいくつ配置するか
plate.row = 1

# ファイル名のプレフィックス
galaxy.file.prefix = galaxy-

# 出力ルートフォルダ（galaxy は自動作成）
output.directory = output

# 白黒反転するか
#   yes: 原板が黒、星が白（エッチング）
#   no: 原板が白、星が黒（リスフィルム）
color.invert = yes
